/**
 * The help index of one language (`help/<language>/index.json`, generated by
 * `scripts/help-pages.mjs`): lower-case mnemonic to page file name, the map of
 * the original `HelpLoader` (spec 09 §1.1).
 */
export type HelpIndex = Readonly<Record<string, string>>;

/** The page of a mnemonic, looked up case-insensitively, or null (spec 02 §11). */
export function lookupHelpPage(index: HelpIndex, mnemonic: string): string | null {
  const key = mnemonic.toLowerCase();
  return Object.hasOwn(index, key) ? index[key] : null;
}

/** What the context help pane shows for the caret line (spec 02 §11). */
export type ContextHelp =
  | { readonly kind: 'page'; readonly mnemonic: string; readonly file: string }
  | { readonly kind: 'missing'; readonly text: string }
  | { readonly kind: 'none'; readonly text: string };

export const NO_HELP_CONTEXT = 'No help available for current context.';

/**
 * The pane content for a line's mnemonic: its page, `No help found for X` when
 * the mnemonic has no page, or `No help available for current context.` when the
 * line has no (known) mnemonic.
 */
export function contextHelpFor(index: HelpIndex, mnemonic: string | null): ContextHelp {
  if (mnemonic === null) return { kind: 'none', text: NO_HELP_CONTEXT };
  const file = lookupHelpPage(index, mnemonic);
  return file
    ? { kind: 'page', mnemonic, file }
    : { kind: 'missing', text: `No help found for ${mnemonic}` };
}

/**
 * The help page a link inside a help page points to (`MOV.htm`, `./mov.htm#x`),
 * as a mnemonic key, or null for anything else (anchors, other sites, scripts).
 */
export function helpLinkTarget(href: string): string | null {
  const match = /^(?:\.\/)?([A-Za-z0-9_]+)\.html?(?:#[\w-]*)?$/.exec(href.trim());
  return match ? match[1].toLowerCase() : null;
}
