#!/usr/bin/env node
/**
 * Bubblesort benchmark for the headless runners.
 *
 *   node bench/bubblesort.mjs asm N       prints the program for N entries
 *   node bench/bubblesort.mjs expect N    prints the expected EAX, EBX and EDI (hex)
 *
 * The program fills N dwords at address 0 with a linear congruential generator
 * (24-bit values), bubble-sorts them in place, then checks the result:
 *   EAX = 1 if the array is in ascending order, else 0
 *   EBX = sum of all entries (mod 2^32)
 *   EDI = sum of entry[i] * (i + 1) (mod 2^32), which also depends on the order
 * `expect` computes the same three values in JavaScript, independently of Jasmin.
 */

const SEED = 12345;
const MUL = 1103515245;
const INC = 12345;

function program(n) {
  return `; Bubblesort of ${n} dwords at address 0 (generated by bench/bubblesort.mjs)
mov eax, ${SEED}
mov ecx, 0
fill:
imul eax, eax, ${MUL}
add eax, ${INC}
mov edx, eax
shr edx, 8
mov [ecx*4], edx
inc ecx
cmp ecx, ${n}
jl fill
mov esi, ${n - 1}
outer:
cmp esi, 0
jle sorted
mov ecx, 0
inner:
mov eax, [ecx*4]
mov ebx, [ecx*4+4]
cmp eax, ebx
jbe noswap
mov [ecx*4], ebx
mov [ecx*4+4], eax
noswap:
inc ecx
cmp ecx, esi
jl inner
dec esi
jmp outer
sorted:
mov eax, 1
mov ebx, 0
mov edi, 0
mov ecx, 0
verify:
mov edx, [ecx*4]
add ebx, edx
mov esi, ecx
inc esi
imul esi, edx
add edi, esi
cmp ecx, ${n - 1}
jae finish
mov esi, [ecx*4+4]
cmp edx, esi
jbe inorder
mov eax, 0
inorder:
inc ecx
jmp verify
finish:
mov ecx, 0
mov edx, 0
mov esi, 0
`;
}

function expected(n) {
  const values = [];
  let x = SEED;
  for (let i = 0; i < n; i++) {
    x = (Math.imul(x, MUL) + INC) | 0;
    values.push(x >>> 8);
  }
  values.sort((a, b) => a - b);
  let sum = 0;
  let weighted = 0;
  values.forEach((v, i) => {
    sum = (sum + v) >>> 0;
    weighted = (weighted + Math.imul(v, i + 1)) >>> 0;
  });
  const hex = (v) => '0x' + v.toString(16).toUpperCase().padStart(8, '0');
  return `EAX=${hex(1)} EBX=${hex(sum)} EDI=${hex(weighted)}`;
}

const [mode, count] = process.argv.slice(2);
const n = Number(count);
if (!Number.isInteger(n) || n < 2 || !['asm', 'expect'].includes(mode)) {
  process.stderr.write('usage: node bench/bubblesort.mjs asm|expect N (N >= 2)\n');
  process.exit(2);
}
process.stdout.write(mode === 'asm' ? program(n) : expected(n) + '\n');
